#### MASINDE VICTOR
#### DATA ANALYST

### CROP YIELDS PROJECT
Food is the most basic need for all living things, including humans. With rising population, shrinking farmland, and climate change, food security needs greater attention. In this project, we will explore different crops, their yields in different soil types and climates, and the effects of fertilizer use.

In [1]:
# Import the necessary libraries to be used
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### 1. DATA UNDERSTANDING
Import data to the notebook and check its general properties.

In [2]:
# Import the dataset to be used for analysis and preview
df = pd.read_csv('crop_yield.csv')
df.head()

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare
0,West,Sandy,Cotton,897.077239,27.676966,False,True,Cloudy,122,6.555816
1,South,Clay,Rice,992.673282,18.026142,True,True,Rainy,140,8.527341
2,North,Loam,Barley,147.998025,29.794042,False,False,Sunny,106,1.127443
3,North,Sandy,Soybean,986.866331,16.644190,False,True,Rainy,146,6.517573
4,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251

In [3]:
# Check for the shape of the dataset
df.shape

(1000000, 10)

In [4]:
# check for the summary information of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 10 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   Region                  1000000 non-null  object
 1   Soil_Type               1000000 non-null  object
 2   Crop                    1000000 non-null  object
 3   Rainfall_mm             1000000 non-null  float64
 4   Temperature_Celsius     1000000 non-null  float64
 5   Fertilizer_Used         1000000 non-null  bool
 6   Irrigation_Used         1000000 non-null  bool
 7   Weather_Condition       1000000 non-null  object
 8   Days_to_Harvest         1000000 non-null  int64
 9   Yield_tons_per_hectare  1000000 non-null  float64
dtypes: bool(2), float64(3), int64(1), object(4)
memory usage: 62.9+ MB

In [5]:
# Check the statistical summary of the dataset
df.describe()

,Rainfall_mm,Temperature_Celsius,Days_to_Harvest,Yield_tons_per_hectare
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,549.981901,27.504965,104.495025,4.649472
std,259.851320,7.220608,25.953412,1.696572
min,100.000896,15.000034,60.000000,-1.147613
25%,324.891090,21.254502,82.000000,3.417637
50%,550.124061,27.507365,104.000000,4.651808
75%,774.738520,33.753267,127.000000,5.879200
max,999.998098,39.999997,149.000000,9.963372

The `crop_yield` dataset has 1,000,000 rows and 10 columns with no missing values. The datatypes present in the dataset are Booleans, object, float and interger. The float and intergers are what makes up the data displayed in the statistical summary.

### 2. Data Cleaning
At this stage we want to ensure our data is ready for analysis and modelling. We check for null values and remove them if any. Duplicates are also dropped at this stage. Fixing data types also happens here and renaming of column names if need be.

In [6]:
# check for nul values in the dataset
df.isnull().sum()

Region                    0
Soil_Type                 0
Crop                      0
Rainfall_mm               0
Temperature_Celsius       0
Fertilizer_Used           0
Irrigation_Used           0
Weather_Condition         0
Days_to_Harvest           0
Yield_tons_per_hectare    0
dtype: int64

In [7]:
# check for duplicates in the dataset
df.duplicated().sum()

0

In [8]:
# Create a column for months taken for the crop to be harvested
df['Months_to_Harvest'] = (df['Days_to_Harvest'] / 30).astype(int)
df.head()

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare,Months_to_Harvest
0,West,Sandy,Cotton,897.077239,27.676966,False,True,Cloudy,122,6.555816,4
1,South,Clay,Rice,992.673282,18.026142,True,True,Rainy,140,8.527341,4
2,North,Loam,Barley,147.998025,29.794042,False,False,Sunny,106,1.127443,3
3,North,Sandy,Soybean,986.866331,16.644190,False,True,Rainy,146,6.517573,4
4,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251,3